import { Details } from "../models/details";

export const MOCK_LISK_DETAILS: Array<Details> = [
  {
    id: 1,
    region: "Moema",
    subway: "Metrô Moema",
    title: "Apartamento com 3 Quarto à Venda, 80 m² por R$ 850.000",
    description: "Apartamento para venda possui 80 metros quadrados com 3 quartos em Moema - São Paulo - São Paulo.",
    area: 80,
    bedrooms: 3,
    distance: "1.8km",
    type: "Apartamento",
    price: 850000,
    img1: "assets/img/prop-1.jpg",
    img2: "assets/img/prop-2.jpg",
    img3: "assets/img/prop-3.jpg",
    condominium: "R$ 600,00",
    iptu: "R$ 800,00",
    advertiser: "AoCubo",
    phone: 11989481090
  },
  {
    id: 2,
    region: "Jardins",
    subway: "Trem Cidade Jardim",
    title: "Apartamento com 3 Quarto à Venda, 110 m² por R$ 1.200.000",
    description: "Apartamento para venda possui 80 metros quadrados com 3 quartos em Jardins - São Paulo - São Paulo.",
    area: 110,
    bedrooms: 3,
    distance: "3.2km",
    type: "Apartamento",
    price: 1200000,
    img1: "assets/img/prop-4.jpg",
    img2: "assets/img/prop-5.jpg",
    img3: "assets/img/prop-6.jpg",
    condominium: "R$ 1.200,00",
    iptu: "R$ 1.600,00",
    advertiser: "AZ Const",
    phone: 11985283290
  },
  {
    id: 3,
    region: "Tatuapé",
    subway: "Metrô Tatuapé",
    title: "Apartamento com 2 Quarto à Venda, 70 m² por R$ 620.000",
    description: "Apartamento para venda possui 80 metros quadrados com 2 quartos em Tatuapé - São Paulo - São Paulo.",
    area: 70,
    bedrooms: 2,
    distance: "2.2km",
    type: "Apartamento",
    price: 620000,
    img1: "assets/img/prop-7.jpg",
    img2: "assets/img/prop-8.jpg",
    img3: "assets/img/prop-9.jpg",
    condominium: "R$ 400,00",
    iptu: "R$ 800,00",
    advertiser: "ATW",
    phone: 11959236270
  },
  {
    id: 4,
    region: "Jardins",
    subway: "Trem Cidade Jardim",
    title: "Apartamento com 2 Quarto à Venda, 86 m² por R$ 1.100.000",
    description: "Apartamento para venda possui 86 metros quadrados com 2 quartos em Jardins - São Paulo - São Paulo.",
    area: 86,
    bedrooms: 2,
    distance: "3.4km",
    type: "Apartamento",
    price: 1100000,
    img1: "assets/img/prop-10.jpg",
    img2: "assets/img/prop-11.jpg",
    img3: "assets/img/prop-12.jpg",
    condominium: "Não Informado",
    iptu: "Não Informado",
    advertiser: "Blue AM",
    phone: 11982167240
  }
]